CREATE DEFINER=`etluser`@`%` PROCEDURE `KilkariMessageMatrixReportQuarter`()
BEGIN
DECLARE dt DATETIME;
DECLARE currdate DATETIME;

SET dt = (select cast(last_etl_time as datetime) from ETL_info_table where table_id = 112);

set currdate = (select cast(CONCAT(YEAR(CURDATE()), '-',  MONTH(CURDATE()), '-01 00:00:00') as datetime));

WHILE dt < currdate DO

truncate table agg_kilkari_message_matrix_quarter_temp;

insert ignore into agg_kilkari_message_matrix_quarter_temp(date, state_id, district_id, healthBlock_id, message_week_group, listened_morethan75, listened_50_75, listened_25_50, listened_lessthan25)
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'mother_week_1_6' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w1_1.wav', 'w2_1.wav', 'w3_1.wav', 'w4_1.wav', 'w5_1.wav', 'w6_1.wav') and call_source = 'OBD' AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id

UNION ALL
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'mother_week_7_12' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w7_1.wav', 'w8_1.wav', 'w9_1.wav', 'w10_1.wav', 'w11_1.wav', 'w12_1.wav') and call_source='OBD'  AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id

UNION ALL
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'mother_week_13_18' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w13_1.wav', 'w14_1.wav', 'w15_1.wav', 'w16_1.wav', 'w17_1.wav', 'w18_1.wav') and call_source='OBD' AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id

UNION ALL
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'mother_week_19_24' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w19_1.wav', 'w20_1.wav', 'w21_1.wav', 'w22_1.wav', 'w23_1.wav', 'w24_1.wav') and call_source='OBD' AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id

UNION ALL
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'child_week_1_6' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w25_1.wav', 'w26_1.wav', 'w27_1.wav', 'w28_1.wav', 'w29_1.wav', 'w30_1.wav') and call_source='OBD' AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id

UNION ALL
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'child_week_7_12' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w31_1.wav', 'w32_1.wav', 'w33_1.wav', 'w34_1.wav', 'w35_1.wav', 'w36_1.wav') and call_source='OBD'  AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id

UNION ALL
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'child_week_13_18' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w37_1.wav', 'w38_1.wav', 'w39_1.wav', 'w40_1.wav', 'w41_1.wav', 'w42_1.wav') and call_source='OBD'  AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id

UNION ALL
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'child_week_19_24' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w43_1.wav', 'w44_1.wav', 'w45_1.wav', 'w46_1.wav', 'w47_1.wav', 'w48_1.wav') and call_source='OBD' AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id

UNION ALL
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'child_week_25_30' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w49_1.wav', 'w50_1.wav', 'w51_1.wav', 'w52_1.wav', 'w53_1.wav', 'w54_1.wav') and call_source='OBD' AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id

UNION ALL
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'child_week_31_36' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w55_1.wav', 'w56_1.wav', 'w57_1.wav', 'w58_1.wav', 'w59_1.wav', 'w60_1.wav') and call_source='OBD' AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id

UNION ALL
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'child_week_37_42' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w61_1.wav', 'w62_1.wav', 'w63_1.wav', 'w64_1.wav', 'w65_1.wav', 'w66_1.wav') and call_source='OBD' AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id

UNION ALL
select dt as date, b.state_id, b.district_id, b.healthBlock_id, 'child_week_43_48' as 'message_week_group', COUNT(case when a.listenedPercentage >= 75 THEN a.beneficiaryTracking_id END) as 'listened_morethan75', COUNT(case when a.listenedPercentage >= 50 and a.listenedPercentage <75 THEN a.beneficiaryTracking_id END) as 'listened_50_75', COUNT(case when a.listenedPercentage >= 25 and a.listenedPercentage <50 THEN a.beneficiaryTracking_id END) as 'listened_25_50', COUNT(case when a.listenedPercentage < 25 THEN a.beneficiaryTracking_id END) as 'listened_lessthan25' from (SELECT a.beneficiaryTracking_id, SUM(a.msg_duration) / SUM(b.message_duration) * 100 AS listenedPercentage FROM beneficiary_call_measure a LEFT JOIN message_durations b ON a.campaign_id = b.id where a.contentFile in ('w67_1.wav', 'w68_1.wav', 'w69_1.wav', 'w70_1.wav', 'w71_1.wav', 'w72_1.wav') and call_source='OBD' AND call_status = 'SUCCESS' and a.modificationDate between dt and DATE_ADD(dt, INTERVAL 3 MONTH) and a.beneficiaryTracking_id is not null GROUP BY beneficiaryTracking_id) as a LEFT JOIN beneficiary_tracker b on a.beneficiaryTracking_id=b.id group by b.state_id, b.district_id, b.healthBlock_id;


insert ignore into agg_kilkari_message_matrix(location_type, location_id, date, message_week_group, listened_morethan75, listened_50_75, listened_25_50, listened_lessthan25,period_type)
select 'NATIONAL' as 'location_type', '0' as 'location_id', date as date, message_week_group, SUM(listened_morethan75), SUM(listened_50_75), SUM(listened_25_50), SUM(listened_lessthan25),'QUARTER' as period_type from agg_kilkari_message_matrix_quarter_temp group by message_week_group
UNION ALL
select 'STATE' as 'location_type', state_id as 'location_id', date as date, message_week_group, SUM(listened_morethan75), SUM(listened_50_75), SUM(listened_25_50), SUM(listened_lessthan25),'QUARTER' as period_type from agg_kilkari_message_matrix_quarter_temp group by state_id, message_week_group
UNION ALL
select 'DISTRICT' as 'location_type', district_id as 'location_id', date as date, message_week_group, SUM(listened_morethan75), SUM(listened_50_75), SUM(listened_25_50), SUM(listened_lessthan25),'QUARTER' as period_type from agg_kilkari_message_matrix_quarter_temp group by district_id, message_week_group
UNION ALL
select 'BLOCK' as 'location_type', healthBlock_id as 'location_id', date as date, message_week_group, SUM(listened_morethan75), SUM(listened_50_75), SUM(listened_25_50), SUM(listened_lessthan25),'QUARTER' as period_type from agg_kilkari_message_matrix_quarter_temp group by healthBlock_id, message_week_group;

SET dt = DATE_ADD(dt, INTERVAL 3 MONTH);
update ETL_info_table set last_etl_time = dt where table_id = 112;

END WHILE;

END
