name: Build and Deploy to Staging
on:
  push:
    branches:
      - deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # Step 3: Build the JAR
      - name: Build with Maven
        run: mvn clean install -f NMSReportingSuite/pom.xml

      # Step 4: Build FrontEnd
      - name: Install Frontend Dependencies and Build with Grunt
        run: |
          cd app
          npm install
          grunt package

      # Step 5: Store deployment data
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            NMSReportingSuite/target/*.war
            app/index.html
            app/scripts/
            app/views/
            app/styles/
            app/dist/


